FROM centos

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app
COPY requirements.txt .
COPY entrypoint.sh .
COPY weather_collector ./weather_collector
RUN yum install -y python3 python3-pip
#RUN python3 -m venv venv
#RUN source venv/bin/activate
RUN /usr/bin/pip3 install --upgrade pip
RUN /usr/bin/pip3 install -r requirements.txt
EXPOSE 8000

#ENTRYPOINT ["/bin/bash", "entrypoint.sh"]
