version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 --workers=5 weather_collector.wsgi --chdir weather_collector/
    env_file:
      - backend/env.list
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
