application : weather_collector
owner       : Alexander_Petrovsky
project     : epam-graduation
environment : Production

frontend:
  port: 80
  container:
    image: petrovsky/frontend:latest

backend:
  port: 8000
  container:
    image: petrovsky/backend:latest

database:
  engine   : django.db.backends.mysql
  name     : weather_collector
  host     : 192.168.88.24
  port     : 3306
