application : weather_collector
owner       : Alexander_Petrovsky
project     : epam-graduation
environment : Production
software_version : 0.0

frontend:
  port: 80
  container:
    image: petrovsky/frontend:{{ software_version }}

backend:
  port: 8000
  container:
    image: petrovsky/backend:{{ software_version }}

database:
  engine   : django.db.backends.mysql
  name     : weather_collector
  host     : 192.168.88.24
  port     : 3306
