apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
     env  : {{ .Values.environment }}
     owner: {{ .Values.owner }}
spec:
  selector:
    project: {{ .Values.project }}-frontend
  type: LoadBalancer
  ports:
    - name      : frontend-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on Pod
