apiVersion : apps/v1
kind: Deployment
metadata:
  name: django-backend
  labels:
    app    : weather_collector
    tier   : backend
    owner  : Aleksandr_Petrovskii1
    project: EPAM_diploma_project
spec:
  selector:
    matchLabels:
      project: EPAM_diploma_project_backend
  template:
    metadata:
      labels:
        project: EPAM_diploma_project_backend
    spec:
      containers:
        - name : django-backend
          image: petrovsky/backend:latest
          ports:
            - containerPort: 8000
          env:
          - name: SECRET_KEY
            value: 'django-insecure-t)8$9v*ampc4h0$2r&ax_zr2b88emo6wm80d^%d_t7sgz5+f9+'
          - name: DJANGO_ALLOWED_HOSTS
            value: "*"
          - name: DEBUG
            value: "1"
          - name: DB_ENGINE
            value: "django.db.backends.mysql"
          - name: DB_NAME
            value: "weather_collector"
          - name: DB_USER
            value: "weather_coll"
          - name: DB_PASSWORD
            value: "weather_collector@123"
          - name: DB_HOST
            value: "192.168.88.24"
          - name: DB_PORT
            value: "3306"


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-backend
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
---

#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: backend-autoscaling
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v2beta1v1
#    kind: Deployment
#    name: django-backend
#  minReplicas: 1
#  maxReplicas: 4
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      targetAverageUtilization: 70
#  - type: Resource
#    resource:
#      name: memory
#      targetAverageUtilization: 80

---























apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
     env  : prod
     owner: Aleksandr_Petrovskii1
spec:
  selector:
    project: EPAM_diploma_project_backend
  type: LoadBalancer
  ports:
    - name      : backend-listener
      protocol  : TCP
      port      : 8000  # Port on Load Balancer
      targetPort: 8000  # Port on Pod

