apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : epam-test-cluster
  region: eu-central-1

vpc:
 id     : "vpc-6c6dfe06"
 subnets:
   public:
      eu-central-1a: { id: subnet-18068254 }  # For Load Balancer
      eu-central-1b: { id: subnet-dc4a30b6 }  # For Load Balancer
      eu-central-1c: { id: subnet-2965d455 }  # For Load Balancer

nodeGroups:
  - name             : worker
    instanceType     : t3.small
    desiredCapacity  : 4
    privateNetworking: false
