apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
     env  : {{ .Values.environment }}
     owner: {{ .Values.owner }}
spec:
  selector:
    project: {{ .Values.project }}-backend
  type: ClusterIP
  ports:
    - name      : backend-listener
      protocol  : TCP
      port      : 8000  # Port on Load Balancer
      targetPort: 8000  # Port on Pod
