apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-django-migrations
#  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
#    "helm.sh/hook": post-upgrade
#    "helm.sh/hook-weight": "-5"
#    "helm.sh/hook-delete-policy": hook-succeeded

  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
#    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "3"


spec:
  template:
    spec:
      containers:
        - name: django-backend
          image: {{ .Values.backend.container.image }}
          command: ['python3', '/usr/src/app/weather_collector/manage.py', 'migrate']
          env:
          - name: SECRET_KEY
            value: 'django-insecure-t)8$9v*ampc4h0$2r&ax_zr2b88emo6wm80d^%d_t7sgz5+f9+'
          - name: DJANGO_ALLOWED_HOSTS
            value: "*"
          - name: DEBUG
            value: "1"
          - name: BACKEND_PORT
            value: "{{ .Values.backend.port }}"
          - name: DB_ENGINE
            value: "{{ .Values.database.engine }}"
          - name: DB_NAME
            value: "{{ .Values.database.name }}"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
          - name: DB_HOST
            value: "{{ .Values.database.host }}"
          - name: DB_PORT
            value: "{{ .Values.database.port }}"
      restartPolicy: Never
  backoffLimit: 5
